Repository c172p-team/c172p, pull requests merged in 2018-11, with the labels that each got.

#1231 Reshape and widen 26" and 36" bush tires to 12" and 15"
  Models/Effects/bushkit/bushkit.xml
  Models/Effects/bushkit/c172p-bushkit.ac
  dev/blender/c172p-bushkit.blend
Labels: 3D model, enhancement, working-on-mesh

#1233 FDM, pitching moment at zero alpha
  c172p.xml
Labels: FDM, enhancement

#1242 Correct JSBSim tag errors
  Systems/c172p-heat.xml
  Systems/c172p-hydrodynamics.xml
  c172p.xml
Labels: FDM, bug
