Repository c172p-team/c172p, pull requests merged in 2018-05, with the labels that each got.

#1078 FDM: pitch moment due to flap deflection
  c172p.xml
Labels: FDM

#1095 Interior upgrades
  Models/Interior/Panel/Instruments/dme/dme.ac
  Models/Interior/Panel/Instruments/dme/dme.xml
  Models/Interior/Panel/Instruments/dme/ki266.ac
  Models/Interior/Panel/Instruments/dme/ki266.xml
  Models/Interior/Panel/Instruments/kr87-adf/kr87.ac
  Models/Interior/Panel/Instruments/kr87-adf/kr87.xml
  dev/blender/instruments/dme.blend
  dev/blender/instruments/ki266.blend
  dev/blender/instruments/kr87.blend
  dev/blender/instruments/kx165-2.blend
Labels: work-in-progress, working-on-mesh

#988 Issue 124: Add engine damage and more advanced oil management
  Models/Effects/damage-smoke/smoke.png
  Models/Effects/damage-smoke/smoke.xml
  Models/Exterior/external-heater/RedDragonEnginePreHeater.ac
  Models/Exterior/external-heater/RedDragonEnginePreHeater.png
  Models/Interior/Panel/Instruments/FuelOilAmps/c172oil.xml
  Models/c172p.xml
  Nasal/c172p.nas
  Nasal/engine.nas
  Nasal/physics.nas
  Systems/c172p-engine.xml
  Systems/engine.xml
  Systems/external-heat.xml
  Systems/fuel.xml
  Systems/instruments.xml
  c172p-set.xml
  c172p.xml
  gui/dialogs/aircraft-dialog.xml
  gui/dialogs/c172p-ground-equipment.xml
  gui/dialogs/c172p-oil-160.xml
  gui/dialogs/c172p-oil-180.xml
Labels: work-in-progress
